export enum RoleMtgEnum {
    HOST = 'HOST',
    CONTROL_BOARD = 'CONTROL_BOARD',
    DIRECTOR_GENERAL_DIRECTOR = 'DIRECTOR_GENERAL_DIRECTOR',
    ADMINISTRATIVE_COUNCIL = 'ADMINISTRATIVE_COUNCIL',
    SHAREHOLDER = 'SHAREHOLDER',
}

export enum TypeRoleMeeting {
    SHAREHOLDER_MTG = 'SHAREHOLDER_MEETING',
    BOARD_MTG = 'BOARD_MEETING',
    BOTH_MTG = 'BOTH_MEETING',
    NULL_MTG = 'NULL_MEETING',
}

export enum RoleBoardMtgEnum {
    HOST = 'HOST',
    CONTROL_BOARD = 'CONTROL_BOARD',
    DIRECTOR_GENERAL_DIRECTOR = 'DIRECTOR_GENERAL_DIRECTOR',
    ADMINISTRATIVE_COUNCIL = 'ADMINISTRATIVE_COUNCIL',
    BOARD = 'BOARD',
}
