export enum TRANSACTION_STATUS {
    PENDING = '1',
    PROCESSING = '2',
    SUCCESS = '3',
    FAILED = '4',
}

export enum TRANSACTION_TYPE {
    CREATE_MEETING = '1',
    UPDATE_PROPOSAL_MEETING = '2',
    UPDATE_USER_PARTICIPATE_MEETING = '3',
    UPDATE_FILE_PROPOSAL_MEETING = '4',
    UPDATE_FILE_OF_MEETING = '5',
    UPDATE_USER_PROPOSAL_MEETING = '6',
}
