/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import type BN from 'bn.js'
import type { ContractOptions } from 'web3-eth-contract'
import type { EventLog } from 'web3-core'
import type { EventEmitter } from 'events'
import type {
    Callback,
    PayableTransactionObject,
    NonPayableTransactionObject,
    BlockType,
    ContractEventLog,
    BaseContract,
} from './types'

export interface EventOptions {
    filter?: object
    fromBlock?: BlockType
    topics?: string[]
}

export type EIP712DomainChanged = ContractEventLog<{}>
export type Initialized = ContractEventLog<{
    version: string
    0: string
}>
export type LogAddValidator = ContractEventLog<{
    _validator: string
    0: string
}>
export type LogRemoveValidator = ContractEventLog<{
    _validator: string
    0: string
}>
export type MeetingCreated = ContractEventLog<{
    _keyMeeting: string
    numberInBlockchain: string
    0: string
    1: string
}>
export type OwnershipTransferred = ContractEventLog<{
    previousOwner: string
    newOwner: string
    0: string
    1: string
}>
export type Paused = ContractEventLog<{
    account: string
    0: string
}>
export type Unpaused = ContractEventLog<{
    account: string
    0: string
}>

export interface Meeting extends BaseContract {
    constructor(
        jsonInterface: any[],
        address?: string,
        options?: ContractOptions,
    ): Meeting
    clone(): Meeting
    methods: {
        CREATE_MEETING_TYPEHASH(): NonPayableTransactionObject<string>

        UPDATE_MEETING_TYPEHASH(): NonPayableTransactionObject<string>

        addValidator(_newValidator: string): NonPayableTransactionObject<void>

        createNoSign(
            _keyMeeting: string,
            _newMeetingHash: [string, string][],
        ): NonPayableTransactionObject<void>

        eip712Domain(): NonPayableTransactionObject<{
            fields: string
            name: string
            version: string
            chainId: string
            verifyingContract: string
            salt: string
            extensions: string[]
            0: string
            1: string
            2: string
            3: string
            4: string
            5: string
            6: string[]
        }>

        getMeetingData(
            _keyMeeting: string,
        ): NonPayableTransactionObject<[[string, string][], string, boolean]>

        getValidators(): NonPayableTransactionObject<string[]>

        initialize(_validator: string[]): NonPayableTransactionObject<void>

        owner(): NonPayableTransactionObject<string>

        pause(): NonPayableTransactionObject<void>

        paused(): NonPayableTransactionObject<boolean>

        removeValidator(_validator: string): NonPayableTransactionObject<void>

        renounceOwnership(): NonPayableTransactionObject<void>

        totalMeeting(): NonPayableTransactionObject<string>

        transferOwnership(newOwner: string): NonPayableTransactionObject<void>

        unpause(): NonPayableTransactionObject<void>
    }
    events: {
        EIP712DomainChanged(cb?: Callback<EIP712DomainChanged>): EventEmitter
        EIP712DomainChanged(
            options?: EventOptions,
            cb?: Callback<EIP712DomainChanged>,
        ): EventEmitter

        Initialized(cb?: Callback<Initialized>): EventEmitter
        Initialized(
            options?: EventOptions,
            cb?: Callback<Initialized>,
        ): EventEmitter

        LogAddValidator(cb?: Callback<LogAddValidator>): EventEmitter
        LogAddValidator(
            options?: EventOptions,
            cb?: Callback<LogAddValidator>,
        ): EventEmitter

        LogRemoveValidator(cb?: Callback<LogRemoveValidator>): EventEmitter
        LogRemoveValidator(
            options?: EventOptions,
            cb?: Callback<LogRemoveValidator>,
        ): EventEmitter

        MeetingCreated(cb?: Callback<MeetingCreated>): EventEmitter
        MeetingCreated(
            options?: EventOptions,
            cb?: Callback<MeetingCreated>,
        ): EventEmitter

        OwnershipTransferred(cb?: Callback<OwnershipTransferred>): EventEmitter
        OwnershipTransferred(
            options?: EventOptions,
            cb?: Callback<OwnershipTransferred>,
        ): EventEmitter

        Paused(cb?: Callback<Paused>): EventEmitter
        Paused(options?: EventOptions, cb?: Callback<Paused>): EventEmitter

        Unpaused(cb?: Callback<Unpaused>): EventEmitter
        Unpaused(options?: EventOptions, cb?: Callback<Unpaused>): EventEmitter

        allEvents(options?: EventOptions, cb?: Callback<EventLog>): EventEmitter
    }

    once(event: 'EIP712DomainChanged', cb: Callback<EIP712DomainChanged>): void
    once(
        event: 'EIP712DomainChanged',
        options: EventOptions,
        cb: Callback<EIP712DomainChanged>,
    ): void

    once(event: 'Initialized', cb: Callback<Initialized>): void
    once(
        event: 'Initialized',
        options: EventOptions,
        cb: Callback<Initialized>,
    ): void

    once(event: 'LogAddValidator', cb: Callback<LogAddValidator>): void
    once(
        event: 'LogAddValidator',
        options: EventOptions,
        cb: Callback<LogAddValidator>,
    ): void

    once(event: 'LogRemoveValidator', cb: Callback<LogRemoveValidator>): void
    once(
        event: 'LogRemoveValidator',
        options: EventOptions,
        cb: Callback<LogRemoveValidator>,
    ): void

    once(event: 'MeetingCreated', cb: Callback<MeetingCreated>): void
    once(
        event: 'MeetingCreated',
        options: EventOptions,
        cb: Callback<MeetingCreated>,
    ): void

    once(
        event: 'OwnershipTransferred',
        cb: Callback<OwnershipTransferred>,
    ): void
    once(
        event: 'OwnershipTransferred',
        options: EventOptions,
        cb: Callback<OwnershipTransferred>,
    ): void

    once(event: 'Paused', cb: Callback<Paused>): void
    once(event: 'Paused', options: EventOptions, cb: Callback<Paused>): void

    once(event: 'Unpaused', cb: Callback<Unpaused>): void
    once(event: 'Unpaused', options: EventOptions, cb: Callback<Unpaused>): void
}
